### ISSUE TITLE
Error: The assembly 'Cake.AzureStorage, Version=0.11.53.0' is referencing an older version of Cake.Core (0.17.0)

### ISSUE THREAD

**Issue by samirem** [cake-contrib/Cake.AzureStorage#17]
Getting the following error when trying to run Cake 0.22, 0.23 or 0.24.
```
Error: The assembly 'Cake.AzureStorage, Version=0.11.53.0, Culture=neutral, PublicKeyToken=null' is referencing an older version of Cake.Core (0.17.0).
This assembly need to reference at least Cake.Core version 0.22.0. Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification by configuring the Skip Verification setting to true (i.e. command line parameter "--settings_skipverification=true", environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true", read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
```

**Comment by phillipsj** [comment]
I apologize for being slow on getting this published.  An updated version should be published today.

**Comment by samirem** [comment]
I'm still getting this problem, but now it says "Cake.AzureStorage, Version=0.11.0.0" instead. Tried to explicitly reference 0.14.0 in Cake through:
#addin nuget:?package=Cake.AzureStorage&version=0.14.0

Am I doing something wrong, or is it not fixed yet? :)

**Comment by medokin** [comment]
It seems to be fixed with https://github.com/RadioSystems/Cake.AzureStorage/pull/21, but there no release yet 😢

**Comment by phillipsj** [comment]
A release should be going out this week.
