### ISSUE TITLE
Ownership of this package

### ISSUE THREAD

**Issue by phillipsj** [cake-contrib/Cake.AzureStorage#24]
@gep13 I don't know if I have any owner privs on this repo, but I will be happy to take this one over. 

Thanks,

Jamie

**Comment by gep13** [comment]
@phillipsj I have just added you as an admin on this repository.  Thanks for your help with it!

**Comment by DaveyBoyCrocky** [comment]
Please remove me from your mailing list.

**Comment by gep13** [comment]
@DaveyBoyCrocky this isn't a mailing list, these are notifications coming from the GitHub Repository located here:

https://github.com/cake-contrib/Cake.AzureStorage

If you are receiving emails from this repository, it must mean that you are subscribed to "watch" it.  Have a look at the top of the repository, where you should see something similar to this:

![image](https://user-images.githubusercontent.com/1271146/61584614-b6720000-ab18-11e9-82cc-0c28b099d3ea.png)

Change that "watch" setting as required.
